config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'tags/:tag', to: 'blogs#index', as: :tag
  resources :blogs
  
  resources :blog_comments

  root 'home#index'
   #resources :contacts
  match '/contacts', to: 'contacts#create', via: [:get, :post]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :blog_comments
	accepts_nested_attributes_for :blog_comments

	acts_as_taggable # Alias for acts_as_taggable_on :tags
  	
end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
	belongs_to :blog
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
	def index
	end

	def create
		BlogComment.create(blog_comment_params)
		redirect_to blog_path(Blog.find(params[:blog_comment][:blog_id]))
	end

	private

	def blog_comment_params
		params.require(:blog_comment).permit!
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    
    @tags = Blog.tag_counts

    if params[:tag]
      @blogs = Blog.tagged_with(params[:tag])
    else
      @blogs = Blog.all
    end

  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @tags = Blog.tag_counts
    @comment = BlogComment.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new()
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :image, :tag_list => [])
    end
end

app/controllers/coming_soon_controller.rb
class ComingSoonController < ApplicationController
	def index
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  #before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # skip_before_filter :verify_authenticity_token, :only => [:ipn_notification]
  respond_to :json
  def create

    @contact = Contact.create(contact_params)
    

    @name = params[:name]
    @email = params[:email]
    @message = params[:message]

    @contact.save

    respond_to do |format|
      if @contact.save
      	ContactMailer.contact_mail(@contact.name, @contact.email, @contact.message).deliver
        format.html { redirect_to :back, notice: 'Message sent' }
        #format.json { render action: 'show', status: :created, location: @contact }
        format.json { redirect_to :back, notice: 'Message sent' }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit! 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def womens_health

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
	
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_footer.html.erb
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center bottom-separator">
                <%= image_tag('home/under.png', class: 'img-responsive inline') %>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="testimonial bottom">
                    <h2>Testimonial</h2>
                    <div class="media">
                        <div class="pull-left">
                            <%= image_tag('testimonial1.jpg', class: 'img-responsive inline img-circle', size: "81x81") %>
                        </div>
                        <div class="media-body">
                            <blockquote>Hicare Pharmacy has been a wonderful asset to our community. The staff is always helpful, courteous and very knowledgeable…Keep up the great work!</blockquote>
                            <h3><a href="#">- Linda P, Belleville</a></h3>
                        </div>
                     </div>
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><%= image_tag('testimonial2.jpg', class: 'img-responsive inline img-circle', size: "81x81") %></a>
                        </div>
                        <div class="media-body">
                            <blockquote>They are great people have a friendly staff! Prices are great! Shop locally is the best. Please support them they have a great crowd and are nice people!”</blockquote>
                            <h3><a href="">- Steven Dodgeville</a></h3>
                        </div>
                    </div>   
                </div> 
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="contact-info bottom">
                    <h2>Contacts</h2>
                    <address>
                    E-mail: <a href="mailto:hicarerx@gmail.com">hicarerx@gmail.com</a> <br> 
                    Phone: <a href="tel:17137998880">+1 (713) 799 8880</a> <br> 
                     
                    </address>

                    <h2>Address</h2>
                    <address>
                    7814 Almeda Rd, <br> 
                    Houston, <br> 
                    Texas, 77054 <br> 
                    USA <br> 
                    </address>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="contact-form bottom">
                    <h2>Send Us a message</h2>
                    <%#= form_for Contact.create, html: {  id: "main-contact-form" } do %>
                    <form id="main-contact-form" action="contacts" method="post" >
                        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                        <div class="form-group">
                            <input type="text" name="contact[name]" class="form-control" required="required" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <input type="email" name="contact[email]" class="form-control" required="required" placeholder="Email address">
                        </div>
                        <div class="form-group">
                            <textarea name="contact[message]" id="message" required="required" class="form-control" rows="8" placeholder="How can we help you?"></textarea>
                        </div>                        
                        <div class="form-group">
                            <input type="submit" name="contact[submit]" class="btn btn-submit" value="Send">
                        </div>
                    </form>
                    <%# end %>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="copyright-text text-center">
                    <p>&copy; Hi-Care Rx 2014. All Rights Reserved.</p>
                    <p>Designed by <a target="_blank" href="http://www.ondo.nyc">Ondo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/application/_header.html.erb
<header id="header">      
    <div class="navbar navbar-inverse" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to root_path, class: "navbar-brand"  do %>
                    <h1><%= image_tag("hicare-logo.png", class: 'img-responsive') %></h1>
                <% end %>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    
                    <li class=""><%= link_to "Blog", blogs_path %></li>
                    <li class=""><%= link_to "Men's Health", page_path('mens-health') %></li>
                    <li class=""><%= link_to "Women's Health(BHRT)", page_path('bhrt') %></li>
                    <li class=""><%= link_to "Veterinary", page_path('veterinary') %></li> 
                    <li class=""><%= link_to "Pain Management", page_path('pain-management') %></li> 
                    <li><a href="#footer">Contact us</a></li>
                                 
                </ul>
            </div>
           
        </div>
    </div>
</header>

app/views/blogs/_blog_sidebar.html.erb
                    <div class="sidebar blog-sidebar">
                        <!-- <div class="sidebar-item  recent">
                            <h3>Comments</h3>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="#"><img src="images/portfolio/project1.jpg" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                    <p>posted on  07 March 2014</p>
                                </div>
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="#"><img src="images/portfolio/project2.jpg" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                    <p>posted on  07 March 2014</p>
                                </div>
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="#"><img src="images/portfolio/project3.jpg" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit,</a></h4>
                                    <p>posted on  07 March 2014</p>
                                </div>
                            </div>
                        </div> -->
                        <!-- <div class="sidebar-item categories">
                            <h3>Categories</h3>
                            <ul class="nav navbar-stacked">
                                <li><a href="#">Lorem ipsum<span class="pull-right">(1)</span></a></li>
                                <li class="active"><a href="#">Dolor sit amet<span class="pull-right">(8)</span></a></li>
                                <li><a href="#">Adipisicing elit<span class="pull-right">(4)</span></a></li>
                                <li><a href="#">Sed do<span class="pull-right">(9)</span></a></li>
                                <li><a href="#">Eiusmod<span class="pull-right">(3)</span></a></li>
                                <li><a href="#">Mockup<span class="pull-right">(4)</span></a></li>
                                <li><a href="#">Ut enim ad minim <span class="pull-right">(2)</span></a></li>
                                <li><a href="#">Veniam, quis nostrud <span class="pull-right">(8)</span></a></li>
                            </ul>
                        </div> -->
                        <div class="sidebar-item tag-cloud">
                            <h3>Tag Cloud</h3>
                            <ul class="nav nav-pills">
                            	<% @tags.each do |tag| %>
								  <li><%= link_to tag.name, tag_path(tag.name) %></li>
								<% end %>
                            </ul>
                        </div>
                        <div class="sidebar-item popular">
                            <h3>Latest Photos</h3>
                            <ul class="gallery">
                                <% Blog.all.last(6).each do |blog| %>
                                <li><%= link_to image_tag(blog.image.thumb), blog %></li>
                                
                                <% end %>
                            </ul>
                        </div>
                    </div>
                

app/views/blogs/_form.html.erb
<%= form_for @blog, html: { multipart: true } do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
  <%= f.label "Blog Image" %><br>
  <%= f.file_field :image %>
  </div>

  <div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list, name: "blog[tag_list][]" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<section id="page-breadcrumb">
        <div class="vertical-center sun">
             <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">Blog</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </section>
    <!--/#page-breadcrumb-->

    <section id="blog" class="padding-top">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                         <div class="col-sm-12 col-md-12">
                          <% @blogs.order('created_at DESC' ).each do |blog| %>
                            <div class="single-blog single-column">
                                <div class="post-thumb">
                                    <%= link_to image_tag(blog.image.large, class: "img-responsive"), blog %>
                                    <div class="post-overlay">
                                       <span class="uppercase"><a href="#"><%= blog.created_at.strftime("%d") %><br><small><%= blog.created_at.strftime("%b") %></small></a></span>
                                   </div>
                                </div>
                                <div class="post-content overflow">
                                    <h2 class="post-title bold"><a href="blogdetails.html"><%= blog.title.split.map(&:capitalize).join(' ') %></a></h2>
                                    <!-- <h3 class="post-author"><a href="#">Posted by micron News</a></h3> -->
                                    <p><%=h truncate(blog.body, :length => 80) %></p>
                                    <%=  link_to "View More", blog %>
                                    <!-- <div class="post-bottom overflow">
                                        <ul class="nav navbar-nav post-nav">
                                            <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                            <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                            <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                                        </ul>
                                    </div> -->
                                </div>
                            </div>
                            <% end %>
                        </div>
                        
                        
                    </div>
                    <!-- <div class="blog-pagination">
                        <ul class="pagination">
                          <li><a href="#">left</a></li>
                          <li><a href="#">1</a></li>
                          <li><a href="#">2</a></li>
                          <li class="active"><a href="#">3</a></li>
                          <li><a href="#">4</a></li>
                          <li><a href="#">5</a></li>
                          <li><a href="#">6</a></li>
                          <li><a href="#">7</a></li>
                          <li><a href="#">8</a></li>
                          <li><a href="#">9</a></li>
                          <li><a href="#">right</a></li>
                        </ul>
                    </div> -->
                 </div>
                 <div class="col-md-3 col-sm-5">
                     <%= render  "blog_sidebar" %>
                </div> 
            </div>
        </div>
    </section>
    <!--/#blog

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<section id="page-breadcrumb">
        <div class="vertical-center sun">
             <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title"><%= @blog.title.split.map(&:capitalize).join(' ') %></h1>
                        </div>                                                                                
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#page-breadcrumb-->

    <section id="blog-details" class="padding-top">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                         <div class="col-md-12 col-sm-12">
                            <div class="single-blog blog-details two-column">
                                <div class="post-thumb">
                                    <%= image_tag(@blog.image.medium, class: "img-responsive")%>
                                    <div class="post-overlay">
                                        <span class="uppercase"><a href="#"><%= @blog.created_at.strftime("%d") %><br><small><%= @blog.created_at.strftime("%b") %></small></a></span>
                                    </div>
                                </div>
                                <div class="post-content overflow">
                                    <!-- <h2 class="post-title bold"><a href="#">Advanced business cards design</a></h2> -->
                                    <!-- <h3 class="post-author"><a href="#">Posted by micron News</a></h3> -->
                                    <p><%= @blog.body %></p>
                                    <!-- <div class="post-bottom overflow">
                                        <ul class="nav navbar-nav post-nav">
                                            <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                            <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                            <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                                        </ul>
                                    </div> -->
                                    <div class="blog-share">
                                        <span class='st_facebook_hcount'></span>
                                        <span class='st_twitter_hcount'></span>
                                        <span class='st_linkedin_hcount'></span>
                                        <span class='st_pinterest_hcount'></span>
                                        <span class='st_email_hcount'></span>
                                    </div>
                                    <!-- <div class="author-profile padding">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img src="images/blogdetails/1.png" alt="">
                                            </div>
                                            <div class="col-sm-10">
                                                <h3>Rodrix Hasel</h3>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi</p>
                                                <span>Website:<a href="www.jooomshaper.com"> www.jooomshaper.com</a></span>
                                            </div>
                                        </div>
                                    </div> -->
                                    <!-- <div class="response-area">
                                    <h2 class="bold">Comments</h2>
                                    <ul class="media-list">
                                        <li class="media">
                                            <div class="post-comment">
                                                <a class="pull-left" href="#">
                                                    <img class="media-object" src="images/blogdetails/2.png" alt="">
                                                </a>
                                                <div class="media-body">
                                                    <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
                                                    <ul class="nav navbar-nav post-nav">
                                                        <li><a href="#"><i class="fa fa-clock-o"></i>February 11,2014</a></li>
                                                        <li><a href="#"><i class="fa fa-reply"></i>Reply</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="parrent">
                                                <ul class="media-list">
                                                    <li class="post-comment reply">
                                                        <a class="pull-left" href="#">
                                                            <img class="media-object" src="images/blogdetails/3.png" alt="">
                                                        </a>
                                                        <div class="media-body">
                                                            <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>
                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut </p>
                                                            <ul class="nav navbar-nav post-nav">
                                                                <li><a href="#"><i class="fa fa-clock-o"></i>February 11,2014</a></li>
                                                            </ul>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </li>
                                        <li class="media">
                                            <div class="post-comment">
                                                <a class="pull-left" href="#">
                                                    <img class="media-object" src="images/blogdetails/4.png" alt="">
                                                </a>
                                                <div class="media-body">
                                                    <span><i class="fa fa-user"></i>Posted by <a href="#">Endure</a></span>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
                                                    <ul class="nav navbar-nav post-nav">
                                                        <li><a href="#"><i class="fa fa-clock-o"></i>February 11,2014</a></li>
                                                        <li><a href="#"><i class="fa fa-reply"></i>Reply</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                        
                                    </ul>                   
                                </div> --><!--/Response-area-->
                                <div class="col-sm-7" style="padding:0;">
                                    <%= simple_form_for @comment do |f|%>
                                        <%= f.input_field :body, class: "form-control", placeholder: "Comments" %>

                                        <%= f.input_field :blog_id, as: :hidden, input_html: { value: @blog.id } %>
                                        <%= f.submit 'Post', class: 'btn btn-submit' %>
                                    <% end %>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
                 <div class="col-md-3 col-sm-5">
                    
                      <%= render  "blog_sidebar" %>
                        
                        
                    
                </div>
            </div>
        </div>
    </section>
    <!--/#blog

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hi-Care Rx</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
   <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDNYCx0Z4PoG2dtzOanU5-DP73o-kWytDg">
    </script> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  



  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- <link rel="shortcut icon" href="<%#= asset_url ('/ico/favicon.ico') %>"> -->
    
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_url ('/ico/apple-touch-icon-144-precomposed.png') %>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_url ('/ico/apple-touch-icon-144-precomposed.png') %>">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_url ('/ico/apple-touch-icon-72-precomposed.png') %>">
    <link rel="apple-touch-icon-precomposed" href="<%= asset_url ('/ico/apple-touch-icon-57-precomposed.png') %>"> 
</head>
<body>
<%= render 'header' %>
<div class="<%= unless params[:controller] == "high_voltage/pages" then params[:controller] else params[:id] end %>">
  <%= yield %>
</div>
<%= render 'footer' %>
</body>
</html>

app/views/pages/womens-health.html.erb
womens health